[package]
name = "atspi-controller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
atspi.workspace = true
futures-lite.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
x11-controller = { path = "../x11-controller" }

[lints]
workspace = true
